curl -O http://s3.amazonaws.com/multiassayexperiments/accMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/blcaMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/brcaMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/cescMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/cholMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/coadMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/dlbcMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/escaMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/gbmMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/hnscMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/kichMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/kircMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/kirpMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/lamlMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/lggMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/lihcMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/luadMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/luscMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/mesoMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/ovMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/paadMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/pcpgMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/pradMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/readMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/sarcMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/skcmMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/stadMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/tgctMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/thcaMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/thymMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/ucecMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/ucsMAEO.rds
curl -O http://s3.amazonaws.com/multiassayexperiments/uvmMAEO.rds

