aws s3 cp ../data/acc_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/acc_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/acc_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/acc_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/acc_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/acc_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/acc_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/acc_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/acc_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/acc_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/acc_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/acc_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/blca_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/brca_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/brca_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/brca_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/brca_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/brca_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/brca_mRNAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/brca_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/brca_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/brca_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/brca_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/brca_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/cesc_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/cesc_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/cesc_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/cesc_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/cesc_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/cesc_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/cesc_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/cesc_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/cesc_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/cesc_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/cesc_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/cesc_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/chol_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/chol_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/chol_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/chol_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/chol_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/chol_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/chol_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/chol_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/chol_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/chol_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/chol_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/chol_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_mRNAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/coad_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/dlbc_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/dlbc_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/dlbc_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/dlbc_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/dlbc_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/dlbc_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/dlbc_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/dlbc_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/dlbc_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/dlbc_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/dlbc_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/dlbc_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/esca_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/esca_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/esca_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/esca_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/esca_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/esca_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/esca_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/esca_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/esca_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/esca_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/esca_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/esca_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/esca_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/gbm_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/gbm_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/gbm_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/gbm_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/gbm_miRNAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/gbm_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/gbm_mRNAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/gbm_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/gbm_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/gbm_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/gbm_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/hnsc_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kich_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kich_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kich_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kich_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kich_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kich_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kich_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kich_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kich_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kich_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kich_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kich_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_mRNAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirc_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_mRNAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/kirp_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/laml_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/laml_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/laml_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/laml_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/laml_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/laml_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/laml_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/laml_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_mRNAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lgg_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lihc_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lihc_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lihc_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lihc_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lihc_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lihc_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lihc_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lihc_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lihc_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lihc_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_mRNAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/luad_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_CNACGH.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_mRNAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/lusc_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/meso_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/meso_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/meso_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/meso_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/meso_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/meso_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/meso_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/meso_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/meso_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/meso_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/meso_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ov_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ov_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ov_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ov_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ov_miRNAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ov_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ov_mRNAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ov_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ov_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ov_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ov_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ov_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/paad_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/paad_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/paad_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/paad_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/paad_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/paad_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/paad_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/paad_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/paad_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/paad_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/paad_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/paad_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/pcpg_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/pcpg_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/pcpg_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/pcpg_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/pcpg_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/pcpg_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/pcpg_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/pcpg_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/pcpg_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/pcpg_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/pcpg_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/pcpg_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/prad_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/prad_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/prad_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/prad_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/prad_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/prad_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/prad_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/prad_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/prad_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/prad_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/prad_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/prad_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/prad_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_mRNAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/read_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/sarc_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/sarc_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/sarc_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/sarc_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/sarc_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/sarc_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/sarc_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/sarc_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/sarc_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/sarc_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/sarc_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/skcm_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/skcm_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/skcm_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/skcm_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/skcm_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/skcm_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/skcm_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/skcm_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/skcm_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/skcm_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/skcm_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/stad_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/tgct_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/tgct_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/tgct_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/tgct_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/tgct_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/tgct_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/tgct_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/tgct_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/tgct_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/tgct_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/tgct_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/tgct_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thca_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thym_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thym_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thym_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thym_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thym_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thym_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thym_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thym_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thym_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thym_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/thym_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_mRNAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_RNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucec_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucs_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucs_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucs_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucs_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucs_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucs_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucs_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucs_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucs_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucs_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucs_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/ucs_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/uvm_CNAseq.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/uvm_CNASNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/uvm_CNVSNP.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/uvm_gistica.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/uvm_gistict.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/uvm_metadata.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/uvm_Methylation.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/uvm_miRNASeqGene.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/uvm_Mutations.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/uvm_pData.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/uvm_RNASeq2GeneNorm.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/uvm_RPPAArray.rda s3://experimenthub/curatedTCGAData/ --acl public-read
aws s3 cp ../data/uvm_sampleMap.rda s3://experimenthub/curatedTCGAData/ --acl public-read
